package dev.underswap1.projectwarpspeed.machine;
@SuppressWarnings("unused")
public enum MachinePartType {

    // Structural
    CASING,
    PLATE,
    REINFORCED_PLATE,
    FRAME,
    BEAM,
    PANEL,
    BRACKET,
    SUPPORT,
    COVER,
    LINING,
    RIB,
    COLUMN,
    BASE,
    MOUNT,
    SLEEVE,
    COLLAR,
    CHANNEL,

    // Fasteners / assembly
    BOLT,
    SCREW,
    NUT,
    RIVET,
    CLAMP,
    HINGE,
    CONNECTOR,
    WASHER,
    LOCK_WASHER,
    PIN,
    DOWEL,
    RETAINER,
    SPRING_PIN,
    CLEVIS,

    // Rotational / transmission parts
    SHAFT,
    AXLE,
    GEAR,
    SMALL_GEAR,
    LARGE_GEAR,
    BEVEL_GEAR,
    WORM_GEAR,
    PINION,
    SPROCKET,
    PULLEY,
    FLYWHEEL,
    CRANK,
    CAM,
    SPINDLE,
    COUPLING,
    TORQUE_ARM,

    // Bearings / support
    BEARING,
    BUSHING,
    SLEEVE_BEARING,
    ROLLER_BEARING,
    THRUST_BEARING,
    JOURNAL,

    // Springs / force parts
    SPRING,
    TORSION_SPRING,
    COMPRESSION_SPRING,
    LEAF_SPRING,

    // Fluid-compatible fabricated parts
    BLADE,
    TURBINE_BLADE,
    IMPELLER,
    NOZZLE,
    VALVE,
    PIPE,
    TUBE,
    MANIFOLD,
    CYLINDER,
    PISTON,
    PLUNGER,
    DIAPHRAGM,

    // Thermal alloy parts
    COIL,
    HEATING_ELEMENT,
    HEAT_SINK,
    BURNER,
    THERMAL_LINING,
    CRUCIBLE,
    RADIATOR,
    THERMOCOUPLE,
    HEAT_EXCHANGER,
    REFRACTORY,

    // Electrical conductive parts
    WIRE,
    CABLE,
    CONTACT,
    ELECTRODE,
    TERMINAL,
    MAGNET,
    SOLENOID,
    BRUSH,
    COMMUTATOR,
    ARMATURE,
    STATOR,
    ROTOR_CORE,
    COIL_WINDING,

    // Processing heads / fabricated tool parts
    CUTTER,
    DRILL,
    HAMMER,
    PRESS,
    MOLD,
    DIE,
    ROLLER,
    GRINDER,
    MILL,
    ANVIL,
    STAMPER,
    CUTTING_HEAD,
    MIXING_BLADE,
    AUGER,

    // Sealing / protection
    SEAL,
    GASKET,
    SHIELD,
    INSULATION,
    LINER,
    BUFFER,
    DAMPING_PAD
}